language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

# BINTRAY_API_KEY and GITHUB_TOKEN
env:
  global:
  - secure: E3QhiwvjofMoxIa3/7JQ5/qI+jd3+GDQDcFnvZq4nsaAM1iBoWpjYOwlkIiGwqtNRx8FShX/1OA6q1LD1gu0k2domi7fIQo7t3PZ102apFAmwgORgZuNeJ2lthhmYx1QovZ5qZdlp03S25HnmH+E44OIOqW01eL9dSl31JIy7rzoILSGv+1Z8za4H7zz+DpqKHq1qvXgZgu19FGpLs3cf3+/g6jEFoI6HxiIdeF39+e1CAhmBvwss6AEsanlgjjT3cTxI34Q//hMntSzJ0uBeKkGQbam7iy+xfQJk+fghthw/msVyn0KBj0OpYm0h4adYOGvjAOJDS/vWdAm3NgvXrV2nPzwYV0JeB+BLLEyQDlAaw0/WUDCk8FUBb4GV8vppsA0Dfzv/TQX25nMw8nMimhCE1MEd3uU6pNzZP/gbnozVDZMjr6HwQjCKVECGBDSEobY4eYUAkpXfL6CqNNNot+h96mtKH2MkNOo3CqrFy9nnsUy2+Ik26LHU3sWaJK0vmIdp/GjwgIFQkfF/MhKyAa1DhDlv9CL87wOvI7ZcRw1/pC7Bv88sExHBf+jGR887072edukKEP9buObNsmo+WiCKBWeKabotHbRl85u3JMVU9+8pTlkHhsjBxnEdCM+7JLEjtKIwILdHNpQ/Wzz2CYWKmdL4lf0DilCoFj0QP0=
  - secure: Gu/VtvTP97Q2GCnE0aEBx+BoJt2jVjb11EHtCahUat0VFTJl3SwcjoJwAtshgNW0tYYz+8xl0AjnqLRL4/DaFiwOX7RZRqcKx0vCClytu/gJt8U6pn1R3QetLsyvLKcmi8DY7JRYl1Z5SYUslvyzZ+mVOk/RAfTKfs4hyjj5fF3qOFyKd4fW2AdJUEoTEK/P8z78Y3E0VSML+DeBOqSCCUkO+34kU/u8n725wrweBlHLGONo0HnwYv68wZuOVVfSHAYO/NB4UgzhssqqYepDEdy0QV8fC4rHxyz/hwnYfVR0KncVl2k/gC5qhPFkydisYJ9k30zARKZ4rCJ63Ma1FyAJ5m1nIVR2a4Nk1DWzxe8w4aLam8Tsv+NCshZHNrHI7rgvRrO6XbcPAgVcPxjDxDkRG9Ob7HdxSm0gIyrxPdWrATSeI5fTmtkcHZyU0UC9KevvoNFgT0z0heQzaa/0AwzR4ep0cnSxsc4AOZzBexUaPEGEwyzRMJ5BfUmeSTroK0F8vh+mJNCXHVkCuxTfgtBNVvqa0NnRwaTPulU134FYUkRgNjMPQUjuXTO08MyRWv4Y39g6jn4nFyjaXi6vEJ+HN01xNhsG35hKds1z/kl3stg0SUMnq/GRAl3xxs47xN3/ByfnD7sc7HkcC1i4DjWi7pHQ8ZSsywxyTxhC6ao=
