language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

env:
  global:
  - secure: NeubSJlNt12PlX72gBmGG7hyDHAHudE7t7mRRvjLJZ7Un/EhPQMqKRGT/Cj/PlmR6fngBA/K6IiQJfh0ZD2ng1+V9jAiViETWb2zW3Wt3OXdiAiqy9Ry0HaCBcH5XTTGvCt9l4XjPYu/A6/+c/6syk4ftj5VmtHiSHozABq+iizhaBKXqoOVY5XABhyzWEB/R8wuzjAwQZn9r/X8/vLNo5nzl/zUvzrtbVUoDdrt24MwJhfcs1i6HWF1oDYNarG3r31WttPuCzVhzywoTqamgcy0OKSY/fNK0+E5YY1gQGGWvECxn/8p1RCAN8t+Dn49ff+9qNOojLqAL5x3K56kABZjdmNEc15r74sTUTZVxsNzhdh5JOwyoK4+MObsGPsaMGU50ieCOc1WUUyX3rnpf0qF8iidzC29GNuduTMC9q9dmOmEOYPNh5/tGT+4rTyexZJpWNmU0m4XLXESIaHi3boa9130LKMG1KVLOZkxjxftxh+V3g2AZme3Ph7BkJquWeAU+PbJ1ZYAJlyXyJPvWk99fGIxpGd9ZLEFsb7A5Iu3FQmHkmZJKtrPpvUQdXy6djMxpZmI3A82+oiwm1NUoiihqMqojS24r7mjV9CMguHKzQ9317NIe608V88JZU48h4Su9YQOa9whPD6UPA3u9O6UN51rYSKl7mu/8lJj0As=
  - secure: jEBzZXgrwez125qIDz09LiAlIviBZg8GU8yyOjVuPGIDFBvDBqAnPrYX6h2hHz5IPAiHnOWOr45mFLaCHnKqG1rvzEdSlAItuuPAgiuahyNbhi1BYa5X89Ze5wXbnkPhHiGwngFEnbC7qyZ+ILveg1ZHquvImfE8gv2IInsNIzyh5c+Wp042V8SClhJJOaRg6py6MURqRI56ROBg8tcpn8blKJwB0fX/ZZGzZvNM+bcW5SRaqEg6oxsNC1Sx5mYhWG9u1UiZflS3r7oYWJLO6piV6jE6QUK3UClquexu8FFkERIvp2Jaw1hOmO4vE4E2TS5mBWEyax554Y8qz0LOcAKqifuJ2VQH5MJaHku3DCAL6tuywcriXm/xfIsr6aqLtF8YtrTecWQEv1ScdlnFPvTgTGVIhZ2hVkJKWm66Bij/KGAZf44QaV1enqQnUVCJW2zpTTnl4LMfXUr9GqfoP+gtR7LKMFtGXQBFX/nko8Ma/czpwmAzW5xGLy10BeHXApcteP0zmhi1isdzsWqecnvl8IF7E5CR0PkPdvUHxfYpLnmpRPL95wt+qSoMk5+PXDnf7x4vFVCOn+/zUHe7M6VEv+wj+yj3jcEpf5oUeaSTTH+T4rhFlNs+IFew5UHMs6ERytnP4yec1g74rPulqwPmiGYNi88HgUnhD9bbOp4=
  - secure: HaJadYqZJc0ImPVpLhCjCIh+oZIZN3sf0M2NErxIrgQ9SV9rfUx1hlixwW8B1aDu+F48psr1VxGyJd2Cd0YMcEgSTzq61dr9SiSs4pNtPJh7692wSwoTy9CJ0MOYwTgDGeq+81j3RlPpaRMViJgTdH9O3dVLiDvmzTFC8wDisUsUTDTkRJ9XIB2E405ds7he20Z+eaqb1dHa6kNjDKgbxO+eDTf67Md85wFWlfxw7SjZrG0jsLnXgDqC8I1IZ/40fIaVZp+PhV4wuAl4bD4LmRVOgthYqjZcsmkm7mVr3g9snZd947l0KRrrWxE0inNvzxZzHGosFFGa+3Jnp/wPNWZWkIatYMRzY8+f7ejnQ/rl57SaTKToUyhlGgYwqWj9jbO7yMPpWa2tSXM/eUwFKKJ3OJwt68gWpbr2c/x5BApcaexzvjO8154DHGd1BzkCtaFec4wkxG4wpXKy5LJvKurRy1ht3y/Z6EJqbHnjwXe2bymsEi0LwmoOP/mCvPfoE/5K/F3AVf5aO929HyrFIemChmyZzMGx10/k+2G7pUwbisRKOewEdRv/SGE4WiH7anbyRoXUteqeEe3netSAkyus9FvRwoUlrt5jIwur36QHicK1XphrLO4MKg3XAbzHPP0OWxo+8Wk2yryVTStBTc1fu9sVx86NtHWlOyObLyQ=
  - secure: CRt5RKISEjVd1DXKevv0qkJZspNk2xmhAfdtX4gOG1Tpwzd3+P27BGdpgk/PhvTTHgzdx+HKyguaE/Gk3StCGaAJKVk7B3lMpishk1KIt7on78sw6AF6otrEltWr7MW9SFC8b0EAklVuqsudBH9k7ZBy48JFCcfwzn0ShAqIMUl2EJoHoN8nxbZfG9jnWwKhXi4RinvTptNxI5+TBNzmSkQZOzTtJXRFO5Ug4sYd58IbwigNDOX/HQZq3fXWnbbGkU/We1K3acC4XSgEHawJQGiIskZ0C+8Exf9gOfGSKhDlSQDE/+yUfPJKbSpkWvwicSSK0aU6FOQNY/RVJdx7PADYW3FjGl3SAUT4p6fWOIf4aBONUyZkNBpMo+44x8YZvm90NAVFxZ9qGADZzIbQnizZPU8poUWhvXsPtWqTlT/E0MYRipuxqaU4O7BsQoRTWo4kaKU8uPt2/+VhkyO0pK93EHTNeFr4hu4V7A5ZQKyEd6HastcrjFUG6cgqoJ5fsVbEvr9V0fsl/6nRLOvcjNSG2+gd//kJcvn1P+Q9wcJJY9Tr9DyP3QeCQIXYR28twdtYSyjUnwujff86uFzI9BB/clQjClSDhRi41Rziie/KINe3uaNlqYaysbGT1lxtZq8Pd881RJdTV2ryVa+T5yiF7KRtoyUhXJXj7mFzo8w=
