language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

env:
  global:
  - secure: NeubSJlNt12PlX72gBmGG7hyDHAHudE7t7mRRvjLJZ7Un/EhPQMqKRGT/Cj/PlmR6fngBA/K6IiQJfh0ZD2ng1+V9jAiViETWb2zW3Wt3OXdiAiqy9Ry0HaCBcH5XTTGvCt9l4XjPYu/A6/+c/6syk4ftj5VmtHiSHozABq+iizhaBKXqoOVY5XABhyzWEB/R8wuzjAwQZn9r/X8/vLNo5nzl/zUvzrtbVUoDdrt24MwJhfcs1i6HWF1oDYNarG3r31WttPuCzVhzywoTqamgcy0OKSY/fNK0+E5YY1gQGGWvECxn/8p1RCAN8t+Dn49ff+9qNOojLqAL5x3K56kABZjdmNEc15r74sTUTZVxsNzhdh5JOwyoK4+MObsGPsaMGU50ieCOc1WUUyX3rnpf0qF8iidzC29GNuduTMC9q9dmOmEOYPNh5/tGT+4rTyexZJpWNmU0m4XLXESIaHi3boa9130LKMG1KVLOZkxjxftxh+V3g2AZme3Ph7BkJquWeAU+PbJ1ZYAJlyXyJPvWk99fGIxpGd9ZLEFsb7A5Iu3FQmHkmZJKtrPpvUQdXy6djMxpZmI3A82+oiwm1NUoiihqMqojS24r7mjV9CMguHKzQ9317NIe608V88JZU48h4Su9YQOa9whPD6UPA3u9O6UN51rYSKl7mu/8lJj0As=
  - secure: jEBzZXgrwez125qIDz09LiAlIviBZg8GU8yyOjVuPGIDFBvDBqAnPrYX6h2hHz5IPAiHnOWOr45mFLaCHnKqG1rvzEdSlAItuuPAgiuahyNbhi1BYa5X89Ze5wXbnkPhHiGwngFEnbC7qyZ+ILveg1ZHquvImfE8gv2IInsNIzyh5c+Wp042V8SClhJJOaRg6py6MURqRI56ROBg8tcpn8blKJwB0fX/ZZGzZvNM+bcW5SRaqEg6oxsNC1Sx5mYhWG9u1UiZflS3r7oYWJLO6piV6jE6QUK3UClquexu8FFkERIvp2Jaw1hOmO4vE4E2TS5mBWEyax554Y8qz0LOcAKqifuJ2VQH5MJaHku3DCAL6tuywcriXm/xfIsr6aqLtF8YtrTecWQEv1ScdlnFPvTgTGVIhZ2hVkJKWm66Bij/KGAZf44QaV1enqQnUVCJW2zpTTnl4LMfXUr9GqfoP+gtR7LKMFtGXQBFX/nko8Ma/czpwmAzW5xGLy10BeHXApcteP0zmhi1isdzsWqecnvl8IF7E5CR0PkPdvUHxfYpLnmpRPL95wt+qSoMk5+PXDnf7x4vFVCOn+/zUHe7M6VEv+wj+yj3jcEpf5oUeaSTTH+T4rhFlNs+IFew5UHMs6ERytnP4yec1g74rPulqwPmiGYNi88HgUnhD9bbOp4=
