language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

env:
  global:
  - secure: MRv46q0X53l5AWGzXwDo26btbdFaDwTJ53sep7Fn5lVMkbpxDQm2nPtVWC4WpAEvWFgHFO8A7pDokwHIbADNv3mJ7K4ByAILTGHvU9FgUNNqAp5dU2Z/bA/avffenNIkOOz3yr6o7T27FJu1C4nPQ1oR5567JpsFj/VtcQwT4azfOuHDkSk7udiA68hV+5BHahnJE6whPxCrYFM0yNjLnkZho/mdUrVSRvJJ/MhEig6dnsXwHGRAx8VlYBBVnwh6NspLIrvPAmZoQXrdAmBX6FNdwDJMWhuIdhYOKbjbVonZW6/Sy5pK+syQRT5HCjH6VQDD6ZY8I6XVjsT49MjQ81hak40YsbKbBd3+iCLyUyY9xPbAjuLNisk8LVlTqFyR+WZvTj/nZv7A6YpOu+9rSBBzoeSW1tk7amHkycp+72rZtaZwqjbEAug8GDbBr7WQFRn4JakPbJW5Zwkhd3MOsWr94w6iSqOPy5bnGSBGeTLdchHB4O/OqCh6CVCIw6gC+Z6Rfy7wWIVhSRQbXMX9ODAlY8DFnLPSF0Nuc2qQyi5iwujwPgYHm7lV/+JpDvdyIYJGzpxDV/bGCq7X9cn/+snMBD/UI3dyqxRue1u8v6RakVMzBUVVHSXw1sV3OrJPyZC693/5rgo2Nt6mNR0OtY1dLZpxNxxhHRQKW/14QmM=
  - secure: cmU6fg7Km4nE+/+O96HYnXE46+QlGhYwtVVMBgKpAonxxt5N2h9ZD6pf8enCUX8vZmg7Q3NdJPO+tNf5DCf+JdZ7X5Aa30tTjnZMT8Fu6BUAMMt7BKdKo0xFTsNZtmNQ7OR8UgP6ulFmu5qwFO5oRrtU90WG98zCfPdEywBQjNIkkqY2yXd4LHS5BFTZQYy3Ik3TwGctKN18P7XtfWjIMl0Niz+z7xUkPt6eV12vKdccMK6XPrkee3BJWODicEvaz4SIB8L0KDMB3MN7Qz87AWuV8N6qzyrhsDrcEkm1kcs4ALdmSgQJFzfCGSBR6SGd7FusBRoJsNHXztU5MC/I8K8XbZdkbM0QsTlBVc0Ahi5jsrdgIgQ3FW1NN8mZ5GWa3AZTUdbYaBwrWlQ1FLdmZft4Zr+ansi9OHT432tKvH/2vSdltAwXI/6VZu7c1yG/vmrEk6PBN8wlVmcuLrf/LBWLTvJ/rfAHmZgrk25PTbfjcGx6TI03kIpQd8kzUCfJOksMX4FqStRk2xNJWApcvZHqi/x0L/u3C5pl1i+AMqvlwN8wluulapyjs4oOqatzWnJxqDMUce6QYyUvzOofkcScivLUEta8drcYGmg5BNp6u0XzdG2krl4GUv/eMJDKFg+LngoKxeOq39h1Cd3MMhdqUpu4DCNyl4MtnZ5LPS4=
  - secure: vRAYGk5prlLKQRzjStw6c/DdeSkzGLzqk+umKY5BsJcVzOj7Om0mKg9ZRhTLf/bPc/QJQ1a4/jU18TgGbppzyHqqlvRXN96hh9YC6+tQift6g+hODut1cDJw8mBGlCVcs21NJo2QAJwoFlK+pdqXYblnPId6zzgrlsnS/Ee/3wTMi6CK0yb96dCLvLa8F3WOs21qsvTY1Zbfy9/6a6dwQAF35D7HysLlLsQ/eRn0AiBwFLTTC30WXw7L96TDfuq0lOpAYVxYXn0cKv1d64HsJZFrXuqzAKRa1kPZ8ktF/pxMLuE2sO2ykeLK63PFSX3YKzp842C+l4pjhPUjHyeSj9CYTYb6Nkft9ko79e3uXRx/cJ9hVzwmk2i/gybbZS018FhQ1tMsH4reY1X9nUgSt0A7075712uC8JVyx4E7iooCMmS3uTcW4PdeOD41CpSlEktPjItXKGIw0GaCxmtbBO6a2SQHP7bNLyMp08ZfeLMyv0OwGMPsfmN4zQh+LPWJ+aaz+0VNhmtk7fUqLGOAzWC0pWcvS8JeGs/+Ou9E6oPao8Tah1G1EgcDVBr4v1FmESIe8dRoJ9QDh1BP/5iQj890UShZ889AjWoLt8iUFN7Wx4BcSuLqtZijvScms+aJEzubEecXqlHLRlQ9AWAt/EvuFhlQDOuxyp2wXBj9FKw=
  - secure: 5gOnB6ag3pej9IHSMuGS9bBXWhZSu28RFRJcllSWYP9AOB9+/XAoBgOnng8KKQp+G08ZpRtK2ujZdSeB/3c+EsgmDa9t4BThpspUvE9HZjDpnpp9m/t1y4aa4blgH+6Pq4JjZCaWEXrzfOLTiYqyHg1Q1jdpqHDfB14wYUIlRIHW06bpCmbqKwC/xFH2SAT/p82RoqOLCIb3llK+viWhN91wf8UsXmf0cTfKm9xM2FeySqLm7h6t8iTyB+spFX+/9thSBLD0+gWn9KnP7ED0aVzVaGTkx1YF64yo3aVa+ghlTDHWb8zYUqTO4cV9V8Q1YtWY6afxCzA6HcoMGvwd6wMedoD/fGhx6uSY+yXpV/N+VaT9/Koq+6nJ8q5qCfmFXCUZU/SQ7Itamt+PGv9+O1Zjq5J/ShBTwudVjajpvs+tPYwRBPJrDcQwWE8XPlwq3XP8/1LKIX8IuM7H8LEmycwh31GJjVrghgWKe6NRnuRj5Z9KIXk8KdH7/U5JjymlZWGGRMBeeZu5GkRt0oKeW8nV+BzJ256AQr+i+1iHqvyatc28v2wTyQfY03D74zmAwG2RXWMWMXbcemHtJF7wpYO4Pbtf52VsaE/TZgwQMlpEk4qtsPqymN/eX0RLbfTsd3Sz3+lo56Kgx+spW0r3ffFmjlJzlUhTPgm33+n0V/U=
